### ISSUE TITLE
Add the possibility to add icons

### ISSUE THREAD

**Issue by diegomolinavera** [eyzy/eyzy-tree#9]
it would be nice to add icons replacing the checkbox. Right now i need that, add a different icon to the parent and the children

**Comment by amsik** [comment]
Hi! You can override the checkbox icon:

```javascript
function MyCheckboxComponent(props) {
  return <span>{props.node.checked ? "+" : "-"}</span>
}
```

```html
 <EyzyTree
    data={[]}
    checkable={true}
    checkboxRenderer={MyCheckboxComponent}
 \>
```

Also it is possible to override a text and arrow (for nodes that has a children). Props:
* textRenderer
* arrowRenderer

**Comment by diegomolinavera** [comment]
@amsik Amezing!
